### ISSUE TITLE
Quiz 3 Question 1

### ISSUE THREAD

**Issue by EthanNicolls** [munkm/npre247#4]
Opening issue for the quiz question.

I found two typos in the textbook, not the notes - they misspelled "ultraviolet" on a diagram and in another, referred to the energy _E_ shown in a diagram when there was only a _V_ in its place. These were in last week's chapters. **Literally unreadable**.

**Comment by munkm** [comment]
Oh _no_!!! I'm glad you were able to overcome the indecency of the authors and post here. 😂 

_excellent_ markdown formatting additions btw
