### ISSUE TITLE
Quiz 3 Question 1

### ISSUE THREAD

**Issue by rileyjfish** [munkm/npre247#6]
Github account acquired. Happy to be here. -Riley Fisher

**Comment by munkm** [comment]
I'm happy you're here too Riley! 

Just wait until we talk about Cerenkov radiation! It's going to be very cool! 

![ATR](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Advanced_Test_Reactor.jpg/911px-Advanced_Test_Reactor.jpg)
